multifactor/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .factors import fido2, totp, fallback


app_name = 'multifactor'

urlpatterns = [
    path('', views.List.as_view(), name="home"),
    path('<str:action>:<slug:ident>/', views.List.as_view(), name="action"),
    path('help/', views.Help.as_view(), name="help"),
    path('authenticate/', views.Authenticate.as_view(), name="authenticate"),
    path('add/', views.Add.as_view(), name="add"),
    path('rename/<int:pk>/', views.Rename.as_view(), name="rename"),

    path('fido2/new/', TemplateView.as_view(template_name='multifactor/FIDO2/add.html'), name="fido2_start"),
    path('fido2/auth/', TemplateView.as_view(template_name='multifactor/FIDO2/check.html'), name="fido2_auth"),
    path('fido2/register/', fido2.Register.as_view(), name="fido2_register"),
    path('fido2/authenticate/', fido2.Authenticate.as_view(), name="fido2_authenticate"),

    path('totp/new/', totp.Create.as_view(), name="totp_start"),
    path('totp/auth/', totp.Auth.as_view(), name="totp_auth"),

    path('fallback/auth/', fallback.Auth.as_view(), name="fallback_auth"),
]

multifactor/templates/multifactor/add.html
{% extends "multifactor/base.html" %}
{% load static %}

{% block card_title %}Add a New Factor{% endblock %}
{% block container_class %}{% endblock %}

{% block content %}

<p>To protect your account and this system from intrusion we request a second verification factor.</p>

<p>There are a range of options. TOTP authenticators are a good first factor because most people always have their phone with them. USB and on-device options might be more secure but have more limited portability.</p>

<div class="columns">
	<div class="column"><div class="card">
		<div class="card-header">
			<h5 class="card-header-title is-centered">FIDO2 Device</h5>
		</div>
		<div class="card-content">
			<p>A broad range of devices: <a href="https://support.microsoft.com/en-gb/help/4028017/windows-learn-about-windows-hello-and-set-it-up">Windows Hello</a> (fingerprint, facial recognition), Google Chrome, Google Android (via biometrics or location), or FIDO2 USB and NFC keys.
			<p>On-device options are convenient but will lock you to that device. USB keys are more portable.</p>
		</div>
		<div class="card-footer">
			<a href="{% url 'multifactor:fido2_start' %}" class="button is-100 is-primary">Add FIDO2 Device</a>
		</div>
	</div></div>
	<div class="column"><div class="card">
		<div class="card-header">
			<h5 class="card-header-title is-centered">TOTP Authenticator</h5>
		</div>
		<div class="card-content">
			<p>Install an authenticator from your phone's marketplace and get access to a secure rotating passcode. Once linked, verification is just a matter of copying that code back into here when prompted.</p>
			<p>Benefits: free, portable.</p>
		</div>
		<div class="card-footer">
			<a href="{% url 'multifactor:totp_start' %}" class="button is-100 is-primary">Add TOTP Authenticator</a>
		</div>
	</div></div>
</div>

{% endblock %}

multifactor/templates/multifactor/authenticate.html
{% extends "multifactor/base.html" %}

{% block card_title %}Multi-Factor Authentication{% endblock %}

{% block content %}
<p class="has-text-centered">You are logged in but you need to verify one of your secondary factors to continue. Which factor would you like to authenticate with?</p>
{% for link, label, factors in methods %}
<a class="button is-primary is-large is-fullwidth is-multilayer" href="{% url link %}">
	<strong>{{label}}</strong>
	<small>{{factors}}</small>
</a>
{% endfor %}

{% if fallbacks %}
</div>
<div class="card-footer">
<a href="{% url 'multifactor:fallback_auth' %}" class="button is-100 button-ml is-light" title="Send a one-time-passcode to all your fallback factors.">
	<strong>Request Fallback Token</strong>
	<small>{{fallbacks|join:" + "}}</small>
</a>
{% endif %}
{% endblock %}

multifactor/templates/multifactor/base.html
<!DOCTYPE html>{% load static %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>{% block title %}Multi-Factor Verification{% endblock %}</title>

	<link href="{% static 'multifactor/multifactor.css' %}" rel="stylesheet">
</head>

<body class="columns"><div class="column {% block container_class %}curt{% endblock %}">

	{% for message in messages %}
	<div class="card-content notification is-{{message.tags}}">
		{{ message }}
	</div>
	{% endfor %}

	{% block page %}
	<div class="card" id="card">
		<div class="card-header">
			{% include "multifactor/brand.html" %}
			<h1 class="">{% block card_title %}{% endblock %}</h1>
		</div>
		<div class="card-content" id="content">
			{% block content %}{% endblock %}
		</div>
	</div>
	{% endblock page %}

	<script src="{%static 'multifactor/multifactor.js' %}"></script>
	{% block head %}
	{% endblock %}
</div></body>
</html>

multifactor/templates/multifactor/help.html
{% extends "multifactor/base.html" %}
{% load static %}

{% block card_title %}Help with Multifactor{% endblock %}
{% block container_class %}{% endblock %}

{% block content %}

<h4>What is multi-factor authentication?</h4>
<p>Traditionally you have logged in with a username and password, maybe directly, maybe through a single sign-in portal. It's a tried and tested authentication system but it's weak. People pick bad passwords, enter them into the wrong places, write them down on paper, give them to the wrong people.</p>

<p>Credentials are <strong>something you know</strong>. Multi-factor authentication adds different types of factor, like <strong>something you have</strong> (a USB security token, your phone), or <strong>something you are</strong> (fingerprint, voice scan, location). For somebody to break in, they would need your credentials <em>and</em> the (eg) Security USB key you keep on your keychain. It dramatically decreases the threat of phishing and data breaches.</p>

<h4>What are fallback factors?</h4>
<p>These are one-time-passcodes over transports like SMS or Email. They <em>are</em> secondary factors but they are usually weaker, more insecure and commonly more inconvenient than plugging in a USB key. They are however, a good defence from getting locked out when your primary factors aren't available.</p>
<p>When you request to authenticate with a secondary factor, we send a the same OTP to all your devices. If you get a message like this and didn't request it, it could mean your main account is compromised.</p>

<h4>What happens if I lose my factor or don't have access to it when I need it?</h4>
<p><strong>Contact your system administrator immediately.</strong> They can deactivate or remove your active factors, allowing you to add another.</p>
<p>We recommend you keep a backup secondary factor. Having a FIDO2 token is convenient (eg just leave your keys plugged in while you're at your computer) but having a TOTP authenticator will serve as a suitable backup if you misplace your keys. Additional factors can dilute over-all security.</p>

{% endblock %}

multifactor/templates/multifactor/home.html
{% extends "multifactor/base.html" %}
{% load static %}

{% block card_title %}Multi-Factor Verification{% endblock %}
{% block container_class %}{% endblock %}

{% block content %}
{% if can_edit %}
<a class="button home-add is-light" href="{% url 'multifactor:add' %}">Add New Factor ➕</a>
{% endif %}

<p>To keep your account secure, you can add one or more secondary authentication factors. These are commonly USB keys, or codes acquired through a secure mechanism like an authenticator. </p>

<table class="table is-striped">
	<tbody>
		{% for factor in factors %}
		<tr>
			<td>
				<h3><a href="{% url 'multifactor:rename' factor.pk %}" title="Click to rename">
					{{ factor.display_name }}
				</a></h3>
				<p>Added {{ factor.added_on.date }}. {% if factor.last_used %}Used {{factor.last_used|timesince}} ago.{% else %}Never used.{% endif %}</p>
			</td>
			<td>
				{% if factor.id in authed_kids %}
					<a class="button disabled" href="#" title="Unlocked">🔓</a>
				{% elif factor.enabled %}
					<a class="button is-light" href="{% url factor.auth_url %}" title="Locked, click to authenticate">🔒</a>
				{% endif %}
				{% if can_edit %}
				<form action="{% url 'multifactor:action' 'toggle_factor' factor.pk %}" method="POST">
					{% csrf_token %}
					<button type="submit" name="kid" value="{{factor.pk}}" class="button is-toggle is-toggled-{{factor.enabled|yesno:'on,off'}}">{{factor.enabled|yesno:'Enabled,Disabled'}}</button>
				</form>
				<form action="{% url 'multifactor:action' 'delete_factor' factor.pk %}" method="POST">
					{% csrf_token %}
					<button type="submit" name="kid" value="{{factor.pk}}" class="button is-danger delete-button"><span>Delete</span></button>
				</form>
				{% endif %}
			</td>
		</tr>
		{% endfor %}
		<tr>
			<td>
				<strong>Fallback verification factors</strong>
				<p>Consider turning these off for higher security.</p>
			</td>
			<td>
				{% csrf_token %}
				{% for fb_name, fb_enabled, fb_destination in available_fallbacks %}
				<form method="POST" action="{% url 'multifactor:action' 'toggle_fallback' fb_name %}">
					{% csrf_token %}
					<button type="submit" class="button button-ml  is-toggle is-toggled-{{fb_enabled|yesno:'on,off'}}" title="{{fb_name}} fallback {{ fb_enabled|yesno:'enabled,disabled' }}, click to toggle." {% if not can_edit %} disabled{% endif %}>
						<span>{{fb_name}} {{ fb_enabled|yesno:'✔,✗' }}</span>
						<small class="d-block">{{fb_destination}}</small>
					</button>
				</form>
				{% endfor %}
			</td>
		</tr>
	</tbody>
</table>
{% endblock %}


{% block head %}{% endblock %}

multifactor/templates/multifactor/userkey_form.html
{% extends "multifactor/base.html" %}
{% load static %}

{% block card_title %}Rename {{object.get_key_type_display}}{% endblock %}

{% block content %}

<p>This step is completely optional. Give your {{object.get_key_type_display}} a better name to help you distinguish it from your other keys.</p>

<form action="" method="POST">
	{% csrf_token %}

	<div class="field"><div class="control">
		<input class="input is-primary has-text-centered is-large" type="text" name="{{form.name.name}}" placeholder="e.g Keyring USB" autocomplete="off" value="{{form.name.value|default:''}}" autofocus>
	</div></div>

	<button type="submit" class="button is-primary is-large is-fullwidth">Update</button>
</form>
{% endblock %}

multifactor/templates/multifactor/verify.html
{% extends "multifactor/base.html" %}

{% block card_title %}Which factor would you like to authenticate with?{% endblock %}

{% block content %}
<p class="has-text-centered">We need to verify one of your secondary factors to continue. Please pick one.</p>
{% for link, label in methods %}
<a class="button is-primary is-large is-fullwidth" href="{% url link %}">{{label}} →</a>
{% endfor %}

{% if fallbacks %}
</div>
<div class="card-footer">
<a href="{% url 'multifactor:fallback_auth' %}" class="button is-100 button-ml is-light">
	<strong>Send Fallback Token</strong>
	<small>{{fallbacks|join:" + "}}</small>
</a>
{% endif %}
{% endblock %}