multifactor/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .factors import fido2, totp, fallback


app_name = 'multifactor'

urlpatterns = [
    path('', views.List.as_view(), name="home"),
    path('<str:action>:<slug:ident>/', views.List.as_view(), name="action"),
    path('help/', views.Help.as_view(), name="help"),
    path('authenticate/', views.Authenticate.as_view(), name="authenticate"),
    path('add/', views.Add.as_view(), name="add"),
    path('rename/<int:pk>/', views.Rename.as_view(), name="rename"),

    path('fido2/new/', TemplateView.as_view(template_name='multifactor/FIDO2/add.html'), name="fido2_start"),
    path('fido2/auth/', TemplateView.as_view(template_name='multifactor/FIDO2/check.html'), name="fido2_auth"),
    path('fido2/register/', fido2.Register.as_view(), name="fido2_register"),
    path('fido2/authenticate/', fido2.Authenticate.as_view(), name="fido2_authenticate"),

    path('totp/new/', totp.Create.as_view(), name="totp_start"),
    path('totp/auth/', totp.Auth.as_view(), name="totp_auth"),

    path('fallback/auth/', fallback.Auth.as_view(), name="fallback_auth"),
]

multifactor/templates/multifactor/FIDO2/add.html
{% extends "multifactor/base.html" %}{% load static %}

{% block card_title %}FIDO2 Security Key{% endblock %}

{% block content %}
<div id="authtype" class="automatic">
	<p class="has-text-centered ">Follow your browser's instructions to continue.</p>
	<button type="button" class="button is-100 is-primary" onclick="authenticate()">Click here to Start</button>
</div>
{% endblock %}

{% block head %}
{{ block.super }}

{% block fido_scripting %}
<script type="module">
import {
	create,
	parseCreationOptionsFromJSON,
} from '{% static 'multifactor/js/webauthn-json.browser-ponyfill.js'%}'

function authenticate() {
	fetch("{% url 'multifactor:fido2_register' %}")
	.then((response) => {
		if(response.ok)
			return response.json()
		throw new Error('Error getting registration data!')
	})
	.then((json) => {
		const options = parseCreationOptionsFromJSON(json)
		return create(options)
	})
	.then((response) => {
		return fetch("{% url 'multifactor:fido2_register' %}", {
			method: 'POST',
			headers: {'Content-Type': 'application/json'},
			body: JSON.stringify(response)
		})
	}, (error) => {
		let el = document.getElementById('authtype')
		el.classList.add('manual')
		el.classList.remove('automatic')
		return Promise.reject(error)
	})
	.then((response) => response.json())
	.then((res) => {
		if (res["status"] =='OK')
			window.location.href = "{% url 'multifactor:home' %}"
		else
			display_error("<p>"+res["message"]+"</p><p><a href='javascript:void(0)' onclick='authenticate()'>try again</a> or <a href='{% url 'multifactor:home' %}'>Go to Multifactor Dashboard</a></p>")
	}, (reason) => {
		display_error("<p>"+reason+"</p><p><a href='javascript:void(0)' onclick='authenticate()'>Try again</a> or <a href='{% url 'multifactor:home' %}'>Go to Multifactor Dashboard</a></p>")
	})
}
window.authenticate = authenticate

setTimeout(authenticate, 500)
</script>
{% endblock fido_scripting %}
{% endblock %}

multifactor/templates/multifactor/FIDO2/check.html
{% extends "multifactor/FIDO2/add.html" %}{% load static %}

{% block fido_scripting %}
<script type="module">
import {
	get,
	parseRequestOptionsFromJSON,
} from '{% static 'multifactor/js/webauthn-json.browser-ponyfill.js'%}'

function authenticate() {
	fetch("{% url 'multifactor:fido2_authenticate' %}")
	.then((response) => {
		if(response.ok)
			return response.json()
		throw new Error('No credential available to authenticate!')
	})
	.then((json) => {
		const options = parseRequestOptionsFromJSON(json)
		return get(options)
	})
	.then((attest) => {
		return fetch("{% url 'multifactor:fido2_authenticate' %}", {
			method: 'POST',
			body: JSON.stringify(attest),
		})
		.then((response) => {
			if (response.ok)
				return response.json()
		})
		.then((res) => {
			if (res.status=="OK") {
				window.location.href = res.redirect
			}
			else {
				display_error("Error occured, please reload to try again.")
			}
		})
	}, (error)  =>{
		var el = document.getElementById('authtype')
		el.classList.add('manual')
		el.classList.remove('automatic')
	})
}
window.authenticate = authenticate

setTimeout(authenticate, 300);
</script>
{% endblock fido_scripting %}

multifactor/templates/multifactor/FIDO2/singlefactor_login.html
{% extends "multifactor/FIDO2/add.html" %}

{% block fido_scripting %}
<script type="text/javascript">
function authenticate() {
	fetch("{% url 'multifactor:singlefactor_begin_auth' %}", {})
	.then(function(response) {
		if(response.ok)
			return response.arrayBuffer();
		throw new Error('No credential available to authenticate!');
	})
	.then(CBOR.decode)
	.then(function(options) {
		return navigator.credentials.get(options);
	})
	.then(function(assertion) {
		console.log(assertion)
		res = CBOR.encode({
			"credentialId": new Uint8Array(assertion.rawId),
			"authenticatorData": new Uint8Array(assertion.response.authenticatorData),
			"clientDataJSON": new Uint8Array(assertion.response.clientDataJSON),
			"signature": new Uint8Array(assertion.response.signature)
		});

		return fetch("{% url 'multifactor:singlefactor_complete_auth' %}", {
			method: 'POST',
			headers: {'Content-Type': 'application/cbor'},
			body: res,
		})
		.then(function (response) {
			if (response.ok)
				return res = response.json()
		})
		.then(function (res) {
			if (res.status=="OK") {
				window.location.href = res.redirect;
			}
			else {
				display_error("Error occured, please reload to try again.")
			}
		})
	})
}

if (location.protocol != 'https:')
	display_error("FIDO2 only works under HTTPS");
else
	setTimeout(authenticate, 500);
</script>
{% endblock fido_scripting %}